[package]
name = "chronobreak_test"
version = "0.1.0"
authors = ["Alexander Linne <alexander.linne@outlook.com>"]
edition = "2018"

[dependencies]
async-std = "1.6"
chronobreak = { path = "../chronobreak" }
