[workspace]
members = [
    "core/codegen",
    "core/globals",
    "core/lib",
    "example",
    "mocks/futures",
    "mocks/futures_timer",
    "mocks/parking_lot",
    "mocks/std",
    "mocks/tests",
]
