[package]
name = "chronobreak_std"
version = "0.1.0"
authors = ["Alexander Linne <alexander.linne@outlook.com>"]
edition = "2018"

[features]
extended-apis = []

[dependencies]
chronobreak = { path = "../../core/lib" }
