[package]
name = "chronobreak_parking_lot"
version = "0.12.0"
authors = ["Alexander Linne <alexander.linne@outlook.com>"]
edition = "2018"

[dependencies]
chronobreak = { path = "../../core/lib" }
parking_lot = { version = "0.12" }
